
GET  http://127.0.0.1:7001/users/getUserDefaultInfo?openid=oBSYU0e306sOf5vlK0LKRIQ_fr30
Content-Type: application/x-www-form-urlencoded

### 
GET  https://api.rightsun.top/getGirl
Content-Type: application/x-www-form-urlencoded


###

GET  http://127.0.0.1:7001/users/getUserDefaultCategory?openid=oBSYU0e306sOf5vlK0LKRIQ_fr30
Content-Type: application/json


### 

GET  http://127.0.0.1:7001/bill/getDetailDataList?openid=oBSYU0e306sOf5vlK0LKRIQ_fr30
Content-Type: application/json

### 

GET  http://127.0.0.1:7001/bill/submitInfo/100003
Content-Type: application/json
### 

DELETE   http://127.0.0.1:7001/bill/submitInfo/100002
Content-Type: application/json

### 

PUT  http://127.0.0.1:7001/bill/submitInfo/100003
Content-Type: application/json

{"deliveryMethod":"6","categoryName":"3","categoryIcon":"soud","tag":"哈哈4","money":69}

### 

GET  http://127.0.0.1:7001/users/checkHasUser?openid=oBSYU0e306sOf5vlK0LKRIQ_fr30
Content-Type: application/json
